version: "3.7"
services:

  # Snapshot hub
  snapshot-hub:
    build: .
    container_name: snapshot-hub
    env_file:
      - .env.local
    depends_on:
      - mysql
    ports:
      - "8087:8080"

  # Snapshot MySQL instance
  mysql:
    image: mysql:8.0.21
    container_name: snapshot-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "snapshot"
    volumes:
        - ./server/helpers/database/:/docker-entrypoint-initdb.d

networks:
  default:
    name: snapshot-network
